# TensorFlow Eager API 的基本介绍

## 什么是TensorFlow Eager API
Eager是一个命令式，运行时定义的TensorFlow接口，在Python中调用这些接口，可以立即执行。这种接口对于上手使用TensorFlow更简单，对于研究和开发也更直观。不管有没有开启Eager API，绝大多数的TensorFlow API保持不变，因此，从TensorFlow图中提取的代码（比如使用layer构建的图）能够直接使用Eager执行，反过来，使用Eager构建的计算图，同样可以进行优化调整，部署到产品中。简单来说，它就是一个更高级的库，可以快捷的上手TensorFlow，使用起来更加直观，而且与其他的高级API通用。

下面这段代码引入Eager库

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as tfe

Instructions for updating:
Use the retry module or similar alternatives.


In [4]:
# 开启Eager API
print("开启Eager模式")
tfe.enable_eager_execution()

开启Eager模式


In [5]:
# 定义常量张量
print("定义常量张量")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

定义常量张量
a = 2
b = 3


In [6]:
# 运行图中操作，不必在session中
print("运行图中操作，不必在session中")
c = a + b
print("a + b = %i" % c)
d = a * b
print("a * b = %i" % d)

运行图中操作，不必在session中
a + b = 5
a * b = 6


In [7]:
# 更复杂的运算：与numpy混合运算
print("更复杂的运算：与numpy混合运算")
a = tf.constant([[2,1],[1,0]], dtype= tf.float32)
print("张量\n %s" % a)
b = np.array([[3,0],[5,1]], dtype = np.float32)
print("numpy数组\n %s" % b)

更复杂的运算：与numpy混合运算
张量
 tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
numpy数组
 [[3. 0.]
 [5. 1.]]


In [9]:
# 不必创建session运行操作
print("不必创建session运行操作")
c = a + b
print("a + b = %s" % c)
d = tf.matmul(a,b)
print("a * b = %s" % d)

不必创建session运行操作
a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [10]:
# 迭代的遍历一个张量
print("迭代的遍历一个张量")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

迭代的遍历一个张量
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
